### ISSUE TITLE
Debugging Research

### ISSUE THREAD

**Issue by Voxel-Friend** [Voxel-Friend/Engineered-Golems#1]
@wamc2017 Think you could help out with this?

**Comment by Voxel-Friend** [comment]
Something is broke here or below: https://github.com/Voxel-Friend/Engineered-Golems/blob/master/src/main/java/com/github/voxelfriend/engineeredgolems/core/CommonProxy.java#L97

**Comment by wamc2017** [comment]
https://github.com/Voxel-Friend/Engineered-Golems/blob/b8add73e3f5a895ae21dbe4b7dbed52b877cd9c0/src/main/resources/assets/engineeredgolems/research/engineeredgolems.json#L13

https://github.com/Voxel-Friend/Engineered-Golems/blob/b8add73e3f5a895ae21dbe4b7dbed52b877cd9c0/src/main/java/com/github/voxelfriend/engineeredgolems/core/CommonProxy.java#L99

I guess those should be the same. ;)

**Comment by Voxel-Friend** [comment]
Ah, nice. good catch.
Also, I'd like to invite you to my discord, if you'd like to join. https://discord.gg/NPRcKSr

**Comment by Voxel-Friend** [comment]
Fixed.
